import React from "react";
import './globals.css'
import { Inter } from 'next/font/google'

import Header from './components/layout/header'
import Body from './components/layout/body'
import Footer from './components/layout/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={`${inter.className}`} >
				<Header />
				{/* <div className="relative w-full h-full">
          <div className="absolute overflow-x-hidden w-[400px] h-full bg-secondary top-[calc(100vh-60px)] left-[calc(50%+300px)] z-[-1]"/>
        </div> */}
				<Body>
					{children}
				</Body>
				{/* <Footer /> */}
			</body>
		</html>
	)
}
